services:
  autodock:
    image: prospero88/autodock:latest
    container_name: vina_experimental
    hostname: auto_dock
    ports:
      - "8501:8501"  # Port open for Streamlit
      - "8001:8001"  # Port open for HTTP serwera
    volumes:
      - C:\Users\aleniak\autodock\dock\results:/root/dock/results
    stdin_open: true
    tty: true
